### ISSUE TITLE
Error compiling typescript

### ISSUE THREAD

**Issue by njfix6** [DataDog/dd-opentelemetry-exporter-js#7]
**Describe the bug**
Cant compile typescript with basic installation

**To Reproduce**
1. Follow the steps on the readme. 
2. Use yarn run 

**Expected behavior**

**Screenshots**
Get the following error:
```
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:43:27 - error TS2345: Argument of type 'DatadogSpanProcessor' is not assignable to parameter of type 'SpanProcessor'.
  The types returned by 'forceFlush()' are incompatible between these types.
    Type 'void' is not assignable to type 'Promise<void>'.

43 provider.addSpanProcessor(processor);
                             ~~~~~~~~~
src/index.ts:47:3 - error TS2741: Property 'fields' is missing in type 'DatadogPropagator' but required in type 'TextMapPropagator<any>'.

47   propagator: new DatadogPropagator(),
     ~~~~~~~~~~

  node_modules/@opentelemetry/api/build/src/context/propagation/TextMapPropagator.d.ts:47:5
    47     fields(): string[];
           ~~~~~~~~~~~~~~~~~~~
    'fields' is declared here.

    at createTSError (/Users/nicholasfix/dev/correlated/graphql-service/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/nicholasfix/dev/correlated/graphql-service/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/nicholasfix/dev/correlated/graphql-service/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/nicholasfix/dev/correlated/graphql-service/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/nicholasfix/dev/correlated/graphql-service/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/nicholasfix/dev/correlated/graphql-service/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
```

**Desktop (please complete the following information):**
 - MAC

**Additional context**

**Comment by ericmustin** [comment]
👋 hey there, sorry for the delay in response. what versions of otel are you using here? This exporter is pretty far behind current opentelemetry-js latest and we plan to update in the very short term.

**Comment by ericmustin** [comment]
@njfix6 We've released a new version if you to try v0.2.0 `https://www.npmjs.com/package/opentelemetry-exporter-datadog`

**Comment by galtomer** [comment]
I'm sorry @ericmustin but the new version doesn't work as well, I get the same issue as @njfix6 .

**Comment by ericmustin** [comment]
@galtomer Thanks for reporting. Will look into this and update the thread. The suggested workaround for the present is to use the opentelemetry-collector and datadogexporter there
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter
- https://docs.datadoghq.com/tracing/setup_overview/open_standards/#opentelemetry-collector-datadog-exporter

**Comment by seanyu4296** [comment]
same issue here +1

**Comment by seanyu4296** [comment]
i think also because this repo uses version  for opentelemetry packages `0.16.0` while the current version for opentelemetry is at `0.21.0` 

maybe we can align the versioning of this package with opentelemetry packages @ericmustin

**Comment by ltudisco** [comment]
+1 I am experiencing the same issue @seanyu4296 reported. Is it possible to upgrade the opentelemetry packages from 0.16.0 to a more recent one please?

**Comment by AndersonQ** [comment]
+1 I'm facing the same problem :/

```
src/opentelemetry/datadog.ts:24:27 - error TS2345: Argument of type 'DatadogSpanProcessor' is not assignable to parameter of type 'SpanProcessor'.
  Types of property 'onStart' are incompatible.
    Type '(span: ReadableSpan) => void' is not assignable to type '(span: Span, parentContext: Context) => void'.
      Types of parameters 'span' and 'span' are incompatible.
        Type 'Span' is not assignable to type 'ReadableSpan'.
          Types of property 'spanContext' are incompatible.
            Type '() => SpanContext' is missing the following properties from type 'SpanContext': traceId, spanId, traceFlags

24 provider.addSpanProcessor(new DatadogSpanProcessor(exporter))
```

**Comment by ericmustin** [comment]
the suggested approach is to use the method documented in that github issue here, send traces through the opentelemetry-collector : https://github.com/DataDog/dd-opentelemetry-exporter-js/issues/7#issuecomment-817603765

in the next datadog agent release (7.30) you will be able to send traces via OTLP directly to a datadog-agent, removing the need for having to use this library, at which point this library will be deprecated.

**Comment by ltudisco** [comment]
Thanks @ericmustin! Is there a timeline for that release? Trying to figure out how to approach open telemetry for a new project.

**Comment by ericmustin** [comment]
@ltudisco coming weeks, roughly speaking. I don't believe the datadog-agent has a specific release schedule but can update this thread when it's out.

repo for reference: https://github.com/DataDog/datadog-agent

**Comment by AndersonQ** [comment]
Thanks @ericmustin, I managed to make it work now after some struggling with the docs. So let me put here how I did it, I hope it will help others :)

On Node.js app:
```
import opentelemetry, {
  DiagConsoleLogger,
  DiagLogLevel,
  diag,
} from '@opentelemetry/api'
import { NodeTracerProvider } from '@opentelemetry/node'
import { Resource } from '@opentelemetry/resources'
import { ResourceAttributes } from '@opentelemetry/semantic-conventions'
import { SimpleSpanProcessor } from '@opentelemetry/tracing'
import { CollectorTraceExporter } from '@opentelemetry/exporter-collector'

const otlpExporter = new CollectorTraceExporter({
  url: 'http://localhost:55681/v1/trace', // url is optional and can be omitted - default is http://localhost:55681/v1/trace
  concurrencyLimit: 10, // an optional limit on pending requests
})

const tracerProvider = new NodeTracerProvider({
  resource: new Resource({ [ResourceAttributes.SERVICE_NAME]: "my-service-name" }),
})

diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.ALL) // for debug

tracerProvider.addSpanProcessor(new SimpleSpanProcessor(otlpExporter))

tracerProvider.register()
```

running the collector on Docker:
```
docker run \
--rm \
--name otel-collector-contrib \
-p 55680:55680 -p 55681:55681 \
-v $(pwd)/otel_collector_config.yaml:/etc/otel/config.yaml \
otel/opentelemetry-collector-contrib --log-level DEBUG --metrics-level detailed --log-profile dev --config /etc/otel/config.yaml
```

my `otel_collector_config.yaml`:

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  datadog/api:
    env: production
    service: my-service-name

    api:
      key: MY_DD_API_KEY
      site: datadoghq.com

service:
  pipelines:
    traces:
      receivers: [otlp]
```
